server:
  port: 8070

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8060/eureka/ #注册中心的注册地址

spring:
  application:
    name: service-provider #服务名称--调用的时候根据名称来调用该服务的方法
  datasource:
    url: jdbc:mysql://47.103.83.230:3306/mysql?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 2009@qazWSX
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:mapperxml/*.xml



logging:
  level:
    #mybatis日志打印级别 对应接口包位置
    com.example.mapper: debug
    #系统日志打印级别
    root: info
